on: [push]
jobs:
  hellow-world-job:
    runs-on: ubuntu-latest
    name: greeting
    steps:
      - name: checkout 
        uses: actions/checkout@v3
      - name: greet people
        id: hellow
        uses: ./
        with:
          who-to-greet: 'whole world'
      - name: print the time of greeting
        run: echo "${{steps.hellow.outputs.time}}"

          

  